source "https://rubygems.org"

# Padrino and Rack are version locked because of this issue:
# https://github.com/padrino/padrino-framework/issues/2288
gem "padrino", "0.15.0"
gem "rack", "2.2.3"

gem "puma"
gem "appsignal", :path => "/integration"
gem "rake"
gem "pry"
