#!/bin/bash

set -eu

echo "Install AppSignal Ruby extension"
(
  cd /integration
  rake extension:install
)

cd /app
echo "Install dependencies"
bundle config set path vendor/bundle
bundle install

echo "Clean tmp"
rm -rf tmp
mkdir -p tmp/pids tmp/sockets

echo "Running migrations"
bin/rails db:migrate

echo "Create sqs queues in mock server"
bundle exec shoryuken sqs create default
bundle exec shoryuken sqs create native
bundle exec shoryuken sqs create batched

/commands/processmon processmon.toml
