version: "3.8"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - mysql.env
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - APPSIGNAL_APP_NAME=nodejs-koa-mysql
    env_file:
      - mysql.env
    volumes:
      - ./app:/app
      - ../../integration:/integration
  tests:
    build: ../../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_URL=http://app:4001
      - APP_NAME=nodejs/koa-mysql
