#!/bin/bash

set -eu

install_opentelemetry_extension_with_pecl() {
  echo "Installing OpenTelemetry extension..."
  pecl install opentelemetry

  # The path here matches the path that `php.ini` is written to in the Dockerfile
  echo "extension=opentelemetry.so" > /etc/php/8.4/cli/conf.d/99-sail.ini
}

install_opentelemetry_extension_with_pie() {
  echo "Installing PHP pie..."
  curl -L https://github.com/php/pie/releases/latest/download/pie.phar -o /usr/local/bin/pie
  chmod +x /usr/local/bin/pie

  echo "Installing OpenTelemetry extension..."
  pie install open-telemetry/ext-opentelemetry

  # No need to add the extension to the php.ini file,
  # as `pie` does this automatically
}

install_opentelemetry_extension_with_pickle() {
  echo "Installing PHP pickle..."
  curl -L https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar -o /usr/local/bin/pickle
  chmod +x /usr/local/bin/pickle

  echo "Installing OpenTelemetry extension..."
  pickle install opentelemetry

  # The path here matches the path that `php.ini` is written to in the Dockerfile
  echo "extension=opentelemetry.so" > /etc/php/8.4/cli/conf.d/99-sail.ini
}

# install_opentelemetry_extension_with_pecl
install_opentelemetry_extension_with_pie
# install_opentelemetry_extension_with_pickle

cd /var/www/html

# Fix file permissions on CI
chmod -R 777 /var/www/html

# Environment variables are passed directly from Docker Compose
# No need to create .env file or unexport variables

echo "Installing dependencies..."
composer install

echo "Starting the application..."
php -S 0.0.0.0:4001 -t public
