version: '3.8'

services:
  app:
    build: .
    image: ruby/sinatra
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=ruby-sinatra-redis
      - PORT=4001
      - REDIS_URL=redis://redis:6379
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
  redis:
    image: redis
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=ruby/sinatra-redis
      - APP_URL=http://app:4001
