services:
  app:
    build: .
    image: ruby/single-task
    environment:
      - APPSIGNAL_APP_NAME=ruby-single-task
      - APPSIGNAL_APP_ENV=development
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
