version: '3.8'

services:
  app:
    build: .
    image: ruby/single-task
    environment:
      - APPSIGNAL_APP_NAME=ruby-single-task
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
