version: '3.8'

services:
  app:
    image: ruby/single-task:latest
    ports:
      - "3000:3000"
    environment:
      - APPSIGNAL_APP_NAME=ruby-single-task
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
