#!/bin/bash

set -eu

echo "Install appsignal"
(
  cd /integration
  git config --global --add safe.directory /integration
  rake extension:install
)

cd /app
echo "Install dependencies"
bundle install
yarn install

echo "Clean tmp"
rm -rf tmp
mkdir -p tmp/pids tmp/sockets

echo "Run migrations"
bin/rails db:migrate
bin/rails sourcemaps

echo "Start app"
/commands/processmon processmon.toml
