#!/bin/bash

set -eu

echo "Checking MongoDB availability"
until nc -z $DATABASE_HOST 27017; do
  >&2 echo "Mongo is unavailable - sleeping"
  sleep 1
done

export DATABASE_URL="mongodb://$DATABASE_HOST:27017/mongo"

echo "Install, link and build integration"
(
cd /integration
git config --global --add safe.directory /integration # avoid git fatal errors about dubious ownership
git checkout main
touch ~/.bashrc # hack to make the mono installer happy
script/setup
mono bootstrap
mono clean
mono run -- npm run install
mono build
)

cd /app

echo "Installing app dependencies"
npm install

echo "Linking integration"
npm link @appsignal/nodejs

echo "Building the app"
npm run build

echo "Running seed"
npm run seed

echo "Starting test app server"
/commands/processmon processmon.toml
