[[paths_to_watch]]
path = "/app"
ignore = [
  "assets/node_modules",
  "_build",
  "priv"
]

[processes.app]
command = "elixir"
args = ["--sname", "server", "--cookie", "server", "-S", "mix", "phx.server"]
working_dir = "/app"
