#!/bin/bash

set -eu

install_opentelemetry_extension_with_pecl() {
  echo "Installing OpenTelemetry extension..."
  pecl install opentelemetry
}

install_opentelemetry_extension_with_pie() {
  echo "Installing PHP pie..."
  curl -L https://github.com/php/pie/releases/latest/download/pie.phar -o /usr/local/bin/pie
  chmod +x /usr/local/bin/pie

  echo "Installing OpenTelemetry extension..."
  pie install open-telemetry/ext-opentelemetry
}

install_opentelemetry_extension_with_pickle() {
  echo "Installing PHP pickle..."
  curl -L https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar -o /usr/local/bin/pickle
  chmod +x /usr/local/bin/pickle

  echo "Installing OpenTelemetry extension..."
  pickle install opentelemetry
}

# install_opentelemetry_extension_with_pecl
# install_opentelemetry_extension_with_pie
install_opentelemetry_extension_with_pickle

# The path here matches the path that `php.ini` is written to in the Dockerfile
echo "extension=opentelemetry.so" > /etc/php/8.4/cli/conf.d/99-sail.ini

cd /var/www/html

# Fix file permissions on CI
chmod -R 777 /var/www/html

function encode() {
  echo -n "$@" | sed 's/,/%2C/g'
}

export OTEL_RESOURCE_ATTRIBUTES="appsignal.config.name=$APPSIGNAL_APP_NAME,\
appsignal.config.environment=$APPSIGNAL_APP_ENV,\
appsignal.config.push_api_key=$APPSIGNAL_PUSH_API_KEY,\
appsignal.config.revision=abcd123,\
appsignal.config.language_integration=php,\
appsignal.config.app_path=$PWD,\
foo.bar=$(encode "123,456"),\
empty.string=,\
baz.qux=%48%65%6C%6C%6F%20%77%6F%72%6C%64%21,\
white.space=Yes please,\
host.name=${HOSTNAME:-$(hostname)}"

echo "Installing dependencies..."
composer install

echo "Migrating database..."

until mysqladmin ping -h${DB_HOST} -u${DB_USERNAME} -p${DB_PASSWORD} --silent; do
  echo "Waiting for database to start..."
  sleep 1
done

echo "Database started!"
/var/www/html/artisan migrate:fresh

start-container
