#!/bin/bash

set -eu

echo "Install appsignal"
cd /integration && rake extension:install

cd /app

echo "Install dependencies"
bundle install --path=vendor/bundle
npm install --prefix=vendor/npm

echo "Clean tmp"
rm -rf tmp

echo "Running migrations"
bin/rails db:migrate
