[[paths_to_watch]]
path = "/app"
ignore = ["prisma/dev.db", "prisma/dev.db-journal", "dist"]

[[paths_to_watch]]
path = "/integration"

[processes.node]
command = "npm"
args = ["run", "start:prod"]
working_dir = "/app"

[triggers.build_integration]
command = "mono"
args = ["build"]
working_dir = "/integration"
