version: '3.8'

services:
  app:
    build: .
    image: ruby/linux-arm
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=ruby-linux-arm
      - APPSIGNAL_BUILD_FOR_LINUX_ARM=1
      - PORT=4001
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=ruby/linux-arm
      - APP_URL=http://app:4001
