version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
  app:
    image: elixir/demo-alpine:latest
    ports:
      - "3000:4000"
    env_file:
      - postgres.env
    volumes:
      - ./app:/app
