# frozen_string_literal: true

source "https://rubygems.org"

gem "appsignal", :path => "/integration"

gem "hanami", "~> 2.2.0"
gem "hanami-router", "~> 2.2.0"
gem "hanami-controller", "~> 2.2.0"
gem "hanami-validations", "~> 2.2.0"
gem "hanami-assets", "~> 2.2"
gem "hanami-view", "~> 2.2"

group :development do
  gem "hanami-webconsole", "~> 2.1"
end

group :test do
  gem "capybara"
end

gem "dry-types", "~> 1.0", ">= 1.6.1"
gem "puma"
gem "rake"

gem "rom", "~> 5.3"
gem "rom-sql", "~> 3.6"
gem "pg"
gem "pry"

group :development, :test do
  gem "dotenv"
end

group :cli, :development do
  gem "hanami-reloader"
end

group :cli, :development, :test do
  gem "hanami-rspec"
end

group :test do
  gem "rack-test"
end
