[[paths_to_watch]]
path = "/app"

[[paths_to_watch]]
path = "/integration"

[processes.hanami]
command = "bundle"
args = [
  "exec",
  "hanami",
  "server",
  "--host=0.0.0.0",
  "--port=4001"
]
working_dir = "/app"
