#!/bin/bash

set -eu

echo "Install, link and build integration"
(
  cd /integration
  script/setup
  mono bootstrap
  mono clean
  mono run --package=@appsignal/nodejs -- npm run install
  mono build
)

cd /app

echo "Install dependencies"
npm install

echo "Npm link in app"
npm link @appsignal/nodejs @appsignal/express

echo "Starting app"
/commands/processmon processmon.toml
