version: "3.8"

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
  app:
    build: .
    image: nodejs/express-postgres
    depends_on:
      - postgres
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - APPSIGNAL_APP_NAME=nodejs-v3-express-postgres
    env_file:
      - postgres.env
      - ../../../appsignal.env
      - ../../../appsignal_key.env
    working_dir: /
    volumes:
      - ./app:/app
      - ../../integration:/integration
  tests:
    build: ../../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_URL=http://app:4001
      - APP_NAME=nodejs/v3/express-postgres
