[[paths_to_watch]]
path = "/app"
ignore = [
  "storage",
  "public",
  "database",
  "bootstrap/cache"
]

[processes.laravel]
command = "composer"
args = [
  "run",
  "dev"
]
working_dir = "/app"

[processes.vite]
command = "./node_modules/vite/bin/vite.js"
working_dir = "/app"
