[[paths_to_watch]]
path = "/app"
ignore = [
  "assets/node_modules",
  "_build",
  "priv"
]

[[paths_to_watch]]
path = "/integration"
ignore = ["appsignal-elixir/priv"]

[processes.app]
command = "mix"
args = ["phx.server"]
working_dir = "/app"
