[[paths_to_watch]]
path = "/app"

[processes.flask]
command = "flask"
args = [
  "run",
  "--host=0.0.0.0",
  "--port=4001"
]
working_dir = "/app"

[processes.consumer]
command = "python"
args = [
  "pika_consumer.py"
]
working_dir = "/app"
