controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

slow:
    path: /slow
    controller: App\Controller\HomeController::slow

error:
    path: /error
    controller: App\Controller\HomeController::error

logs:
    path: /logs
    controller: App\Controller\HomeController::logs

metrics:
    path: /metrics
    controller: App\Controller\HomeController::metrics
