version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    image: javascript/vanilla
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=javascript-vanilla
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
      - appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=javascript/vanilla
      - APP_URL=http://app:4001
