version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    image: javascript/vanilla
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=javascript-vanilla
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
      - appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
