#!/bin/sh

set -eu

echo "Install appsignal"
(
  set -eu
  cd /integration
  rake extension:install
)

echo "Install dependencies"
(
  set -eu
  cd /app
  bundle config set --local path 'vendor/bundle'
  bundle install
)

echo "Create sqs queues"
(
  cd /app
  # Create queues in mock server
  bundle exec shoryuken sqs create default
  bundle exec shoryuken sqs create batched
)
