#!/bin/bash

set -eu

echo "Install appsignal"
(
  cd /integration
  rake extension:install
)

cd /app
echo "Install dependencies"
bundle config set --local path 'vendor/bundle'
bundle install

echo "Create sqs queues in mock server"
bundle exec shoryuken sqs create default
bundle exec shoryuken sqs create batched

/commands/processmon processmon.toml
