#!/bin/bash

set -eu

echo "Install, link and build integration"
(
  cd /integration
  git checkout 2-4-stable
  script/setup
  source ~/.bashrc
  mono bootstrap
  mono build
)

cd /app

echo "Install dependencies"
npm install

echo "Npm link in app"
npm link @appsignal/nodejs @appsignal/express @appsignal/apollo-server
