#!/bin/bash
set -eu

echo "Install, link and build integration"
(
  cd /integration
  script/setup
  script/build
)

echo "Npm link in app"
cd /app && npm link @appsignal/nodejs
cd /app && npm link @appsignal/express

echo "Install dependencies"
cd /app && npm install
