include:
  - path: docker-compose.shared.yml
  - path: ../../support/collector/docker-compose.yml

services:
  app:
    environment:
      - APPSIGNAL_APP_NAME=ruby/rails8-que-collector
      - APPSIGNAL_COLLECTOR_ENDPOINT=http://appsignal-collector:8099
  downstream:
    environment:
      - APPSIGNAL_APP_NAME=ruby/rails8-que-downstream-collector
      - APPSIGNAL_COLLECTOR_ENDPOINT=http://appsignal-collector:8099
