services:
    app:
        entrypoint: '/commands/run'
        build:
            context: './docker'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '1000'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '5173:5173'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'off'
            XDEBUG_CONFIG: 'client_host=host.docker.internal'
            IGNITION_LOCAL_SITES_PATH: '${PWD}/app'
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PASSWORD: password
            DB_USERNAME: laravel
            APP_DEBUG: 'true'
            APP_ENV: local
            APP_KEY: 'J0TeTiVkAlJ2eUndVMKCi5EGjNPittlM'
        volumes:
            - './app:/var/www/html'
            - './commands:/commands'
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'laravel'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './docker/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-ppassword'
            retries: 3
            timeout: 5s
