#!/bin/bash
set -eu

(
  echo "Install, link and build integration"
  cd /integration
  script/setup
  mono bootstrap
  mono build
)

cd /app

echo "Install dependencies"
yarn install
yarn link @appsignal/types @appsignal/javascript @appsignal/plugin-window-events @appsignal/webpack

npm install -g http-server

echo "Host running"
echo "To test the app, run the following command:"
echo "  rake app=javascript/webpack app:console"
echo "Exit the console command to stop the server, and run it again to restart the server for a new release."

if [ ! -f REVISION ]; then
  # Create release file with first release version if missing
  echo "release0" > REVISION
fi

tail -f /dev/null # Keep container alive so you can bash into it
