version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
  app:
    image: elixir/alpine-release:latest
    depends_on:
      - postgres
    ports:
      - "4001:4000"
    environment:
      - APPSIGNAL_APP_NAME=elixir-alpine-release
    env_file:
      - postgres.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
