version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - mysql.env
  app:
    build: .
    image: python/fastapi-databases
    ports:
      - "4001:4001"
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
      - postgres.env
      - mysql.env
    environment:
      - PORT=4001
      - APPSIGNAL_APP_NAME=python/fastapi-databases
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=python/fastapi-databases
      - APP_URL=http://app:4001
