version: '3.8'

services:
  appsignal-collector:
    image: appsignal/collector:latest
    environment:
      - APPSIGNAL_LOG_LEVEL=trace
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    image: javascript/react-vite-collector
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=javascript/react-vite-collector
      - APPSIGNAL_APP_ENV=development
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
  cors:
    build: ./cors
    ports:
      - "8099:80"
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=javascript/react-vite-collector
      - APP_URL=http://app:4001
