{application,appsignal_plug,
             [{compile_env,[{appsignal,[appsignal_span],error}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,plug,appsignal,
                             telemetry,hackney]},
              {description,"AppSignal's Plug instrumentation instruments calls to Plug applications to gain performance insights and error reporting"},
              {modules,['Elixir.Appsignal.Metadata.Plug.Conn',
                        'Elixir.Appsignal.Plug']},
              {registered,[]},
              {vsn,"2.0.15"}]}.
