include:
  - path: docker-compose.shared.yml
  - path: ../../support/collector/docker-compose.yml

services:
  app:
    environment:
      - APPSIGNAL_APP_NAME=python/flask-pika-collector
      - APPSIGNAL_SERVICE_NAME=app
      - APPSIGNAL_COLLECTOR_ENDPOINT=http://appsignal-collector:8099
  worker:
    environment:
      - APPSIGNAL_APP_NAME=python/flask-pika-collector
      - APPSIGNAL_SERVICE_NAME=worker
      - APPSIGNAL_COLLECTOR_ENDPOINT=http://appsignal-collector:8099
