include:
  - path: docker-compose.shared.yml

services:
  app:
    environment:
      - APPSIGNAL_APP_NAME=ruby-rails7-goodjob
  worker:
    environment:
      - APPSIGNAL_APP_NAME=ruby-rails7-goodjob-worker
