version: '3.8'

services:
  postgres:
    image: postgres:16.0
    env_file:
      - postgres.env
  app:
    build: .
    image: ruby/hanami2-postgres
    depends_on:
      - postgres
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=ruby-hanami2-postgres
      - PORT=4001
      - PGHOST=postgres
      - PGDATABASE=app_db
      - PGUSER=app
      - PGPASSWORD=password
      - DATABASE_URL=postgres://app:password@postgres:5432/app_db
    env_file:
      - postgres.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=ruby/hanami2-postgres
      - APP_URL=http://app:4001
