#!/bin/bash

set -eu

echo "Install, link and build integration"
(
  cd /integration
  npm install
  npm run build
  npm link
)

cd /app

echo "Install dependencies"
npm install

echo "Npm link in app"
npm link @appsignal/nodejs

echo "Starting app"
/commands/processmon processmon.toml
