include:
  - path: docker-compose.shared.yml

services:
  app:
    environment:
      - APPSIGNAL_APP_NAME=python/django5-celery
  downstream:
    environment:
      - APPSIGNAL_APP_NAME=python/django5-celery-downstream
  worker:
    environment:
      - APPSIGNAL_APP_NAME=python/django5-celery-worker
