#!/bin/ash
set -eu

echo "Install appsignal"
(
  cd /integration
  rake extension:install
)

cd /app

echo "Install dependencies"
bundle config set path vendor/bundle
bundle install

echo "Starting app"
/commands/processmon processmon.toml
