#!/bin/bash

set -eu

echo "Install, link and build integration"
(
  cd /integration
  npm install
  npm run build
  npm link
)

cd /app

echo "Installing app dependencies"
npm install

echo "Linking integration"
npm link @appsignal/nodejs

echo "Building app"
npm run build

echo "Starting test app server"
/commands/processmon processmon.toml
