#!/bin/bash

set -eu

pip3 install --upgrade pip

cd /integration

pip3 install hatch
hatch clean
_APPSIGNAL_BUILD_COLLECTOR_PATH=--keep-collector _APPSIGNAL_BUILD_COLLECTOR_ENABLED=1 _APPSIGNAL_BUILD_AGENT_ENABLED=0 hatch run build:me

cd /app

echo "Installing dependencies"
pip3 install -r requirements.txt
pip3 install /integration/dist/* --force-reinstall

echo "Running migrations"
python3 manage.py migrate

echo "Starting app"
/commands/processmon processmon.toml
