default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  pool: 5
  username: app
  password: password

development:
  <<: *default
  database: app_db

test:
  <<: *default
  database: app_db

production:
  <<: *default
  database: sample_postgres_production
