#!/bin/bash
set -eu

echo "Install appsignal"
cd /integration
rake extension:install

echo "Install dependencies"
cd /app
bundle install

echo "Run migrations"
bundle exec rake db:setup
bundle exec rake db:migrate

/commands/processmon processmon.toml
