#!/bin/bash

set -eu

echo "Install link and build integration"
(
cd /integration
git config --global --add safe.directory /integration # avoid git fatal errors about dubious ownership
touch ~/.bashrc # hack to make the mono installer happy
script/setup
mono bootstrap
mono clean
mono run -- npm run install
mono build
)

cd /app

echo "Installing app dependencies"
npm install

echo "Linking integration"
npm link @appsignal/nodejs

echo "Building the app"
npm run build

echo "Starting test app server"
 /commands/processmon processmon.toml
