paths_to_watch = [
  "/app",
  "/integration"
]

[processes]

[processes.node]
command = "node"
args = ["server.js"]
working_dir = "/app"

[triggers]

[triggers.build_integration]
command = "./script/build"
working_dir = "/integration"
