version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    image: javascript/typescript-angular
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=javascript-typescript-angular
      - PORT=4001
    env_file:
      - app.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
