#!/bin/bash
set -eu

echo "Install appsignal"
cd /integration
rake extension:install

echo "Install dependencies"
cd /app
bundle config set --local path 'vendor/bundle'
bundle install

echo "Run single task. Will exit afterwards."
# Run with warnings enabled, verbose mode
bundle exec ruby -W2 app.rb
