#!/bin/bash

set -eu

echo "Create posts table if needed"
host="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB"
until psql $host --command='\l'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

psql $host \
  --command "CREATE TABLE IF NOT EXISTS posts (id SERIAL, title varchar(80), text text);"

echo "Install, link and build integration"
(
  cd /integration
  git checkout 2-4-stable
  script/setup
  mono bootstrap
  mono clean
  mono run --package=@appsignal/nodejs -- npm run install
  mono build
)

cd /app

echo "Install dependencies"
npm install

echo "Npm link in app"
npm link @appsignal/nodejs @appsignal/express

echo "Starting app"
/commands/processmon processmon.toml
