#!/bin/bash
set -eu

(
  echo "Install, link and build integration"
  cd /integration
  script/setup
  mono bootstrap
  mono build --package=@appsignal/types,@appsignal/core,@appsignal/javascript,@appsignal/angular,@appsignal/webpack
)

cd /app

echo "Install dependencies"
npm install
npm link @appsignal/types @appsignal/core @appsignal/javascript @appsignal/angular @appsignal/webpack

echo "Host running"
echo "To test the app, run the following command:"
echo "  rake app=javascript/typescript-angular app:console"
echo "Exit the console command to stop the server, and run it again to restart the server for a new release."

if [ ! -f REVISION ]; then
  # Create release file with first release version if missing
  echo "release0" > REVISION
fi

tail -f /dev/null # Keep container alive so you can bash into it
