#!/bin/bash

set -eu

echo "Install, link and build integration"
(
  cd /integration
  git checkout main
  touch ~/.bashrc # hack to make the mono installer happy
  script/setup
  mono bootstrap
  mono clean
  mono run -- npm run install
  mono build
)

cd /app

echo "Install dependencies"
npm install

echo "Npm link in app"
npm link @appsignal/nodejs

echo "Starting app"
/commands/processmon processmon.toml
