version: '3.8'

services:
  app:
    build: .
    image: nodejs/koa
    ports:
      - "4001:3000"
    environment:
      - APPSIGNAL_APP_NAME=nodejs-koa
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
