version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
  redis:
    image: "redis:7.4.2"
  app:
    build: .
    image: ruby/rails8-sidekiq
    depends_on:
      - postgres
      - redis
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=ruby/rails8-sidekiq
      - PORT=4001
    env_file:
      - postgres.env
      - redis.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=ruby/rails8-sidekiq
      - APP_URL=http://app:4001
