include:
  - path: docker-compose.shared.yml

services:
  app:
    environment:
      - APPSIGNAL_APP_NAME=python/django4-asgi
  downstream:
    environment:
      - APPSIGNAL_APP_NAME=python/django4-asgi-downstream
