default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "<%= ENV['APPSIGNAL_APP_NAME'] %>"
development:
  <<: *defaults
  active: true
production:
  <<: *defaults
  active: true
