defmodule Helpdesk.Support.Ticket do
  use Ash.Resource,
    otp_app: :app,
    domain: Helpdesk.Support

  actions do
    # Use the default implementation of the :read action
    defaults([:read])

    # and a create action, which we'll customize later
    create :create
  end

  # Attributes are the simple pieces of data that exist on your resource
  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key(:id)

    # Add a string type attribute called `:subject`
    attribute(:subject, :string)
  end
end
