version: '3.8'

services:
  app:
    build: .
    image: javascript/webpack
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - APPSIGNAL_APP_NAME=javascript-webpack
    env_file:
      - app.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
