version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
  redis:
    image: "redis:6.2.7"
    ports:
      - "6379:6379"
  appsignal:
    image: appsignal/agent:latest
    ports:
      - "8099:8099"
    env_file:
      - ../../appsignal_key.env
    environment:
      - APPSIGNAL_APP_NAME=python/django4-celery
      - APPSIGNAL_APP_ENV=development
      - APPSIGNAL_LOG_LEVEL=trace
  app:
    build: .
    image: python/django4-celery
    depends_on:
      - appsignal
      - postgres
    ports:
      - "4001:4001"
    env_file:
      - postgres.env
    environment:
      - PORT=4001
    volumes:
      - ./app:/app
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=python/django4-celery
      - APP_URL=http://app:4001
