version: '3.8'

services:
  app:
    build: .
    image: javascript/vue-3-ts
    ports:
      - "4001:3000"
    environment:
      - APPSIGNAL_APP_NAME=javascript-vue-3-ts

    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=javascript/vue-3-ts
      - APP_URL=http://app:3000
