#!/bin/bash

set -eu

echo "Install, link and build integration"
(
  cd /integration
  rm -f /integration/packages/nodejs-ext/ext/appsignal-agent
  script/setup
  mono bootstrap
  mono build
)

cd /app

echo "Install dependencies"
npm install

echo "Npm link in app"
npm link @appsignal/nodejs @appsignal/koa
