[[paths_to_watch]]
path = "/app"
ignore = ["tmp", "log", "public/packs", "node_modules/.cache"]

[[paths_to_watch]]
path = "/integration"

[processes.shoryuken]
command = "bundle"
args = [
  "exec",
  "shoryuken",
  "-q=default",
  "-R"
]
working_dir = "/app"

[processes.rails]
command = "bin/rails"
args = [
  "server",
  "--binding=0.0.0.0"
]
working_dir = "/app"
