#!/bin/bash

set -eu

# Because of an issue with Next.js' internal use of Webpack and `npm link`-ed
# projects, instead of using `npm link`, we copy the built integration to
# the app's node_modules directory.

echo "Install and build integration"
(
  cd /integration
  npm install
  npm run build
)

cd /app

echo "Installing app dependencies"
npm install

# See comment above.

rm -rf /app/node_modules/@appsignal/nodejs
cp -r /integration /app/node_modules/@appsignal/nodejs

echo "Starting the app in NODE_ENV='$NODE_ENV' (default: development)"
if [ "$NODE_ENV" == "production" ]; then
  npm run build
  npm run start
else
  npm run dev
fi
