version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - 5432
  appsignal-collector:
    image: appsignal/collector:latest
    environment:
      - APPSIGNAL_LOG_LEVEL=trace
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
  app:
    build: .
    image: elixir/phoenix-collector
    depends_on:
      - postgres
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - APPSIGNAL_APP_NAME=elixir/phoenix-collector
    env_file:
      - postgres.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=elixir/phoenix-collector
      - APP_URL=http://app:4001
