#!/bin/bash
set -eu

echo "Install appsignal"
(
  cd /integration
  rake extension:install
)

cd /app

# Paths for Puma
mkdir -p shared/sockets shared/pids shared/log

echo "Install dependencies"
bundle config set path vendor/bundle
bundle install

echo "Starting app"
# /commands/processmon processmon.toml
bundle exec puma -C config/puma.rb --environment production
