version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./app:/app
    environment:
      # APPSIGNAL_APP_NAME: java/spring-agent-collector
      APPSIGNAL_APP_NAME: Stroopwafel BV
      APPSIGNAL_APP_ENV: production
      SERVER_PORT: "4001"
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    ports:
      - "4001:4001"
    depends_on:
      - appsignal-collector
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  appsignal-collector:
    image: appsignal/collector:latest
    environment:
      - APPSIGNAL_LOG_LEVEL=trace
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
  tests:
    image: server-tests
    build: ../../support/server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=java/spring-agent-collector
      - APP_URL=http://app:4001

volumes:
  elasticsearch_data:
