version: '3.8'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - mysql.env
  redis:
    container_name: redis
    image: redis
    restart: always
  app:
    build: .
    image: nodejs/opentelemetry
    ports:
      - "4001:3000"
    environment:
      - APPSIGNAL_APP_NAME=nodejs-opentelemetry
    env_file:
      - mysql.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=nodejs/opentelemetry
      - APP_URL=http://app:3000
