#!/bin/bash
set -eu

(
  echo "Install, link and build integration"
  cd /integration
  script/setup
  mono bootstrap
  mono build --package=@appsignal/types,@appsignal/core,@appsignal/javascript
)

cd /app

echo "Install dependencies"
npm install
npm link @appsignal/types @appsignal/core @appsignal/javascript

echo "Starting app"
npm run server
