version: '3.8'

services:
  motoserver:
    image: motoserver/moto
    ports:
      - "5000:5000"
  app:
    image: ruby/shoryuken:latest
    depends_on:
      - motoserver
    ports:
      - "3000:3000"
    environment:
      - APPSIGNAL_APP_NAME=ruby-shoryuken
    env_file:
      - shoryuken.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
