version: '3.8'

services:
  motoserver:
    image: motoserver/moto
  app:
    build: .
    image: ruby/shoryuken
    depends_on:
      - motoserver
    environment:
      - APPSIGNAL_APP_NAME=ruby-shoryuken
    env_file:
      - shoryuken.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - "nfsmount_app:/app"
      - "nfsmount_integration:/integration"

volumes:
  nfsmount_app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/app"
  nfsmount_integration:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/../integration"
    volumes:
