version: '3.8'

services:
  motoserver:
    image: motoserver/moto
  app:
    build: .
    image: ruby/shoryuken
    depends_on:
      - motoserver
    environment:
      - APPSIGNAL_APP_NAME=ruby-shoryuken
    env_file:
      - shoryuken.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
