[[paths_to_watch]]
path = "/app"

[[paths_to_watch]]
path = "/integration"

[processes.node]
command = "npm"
args = ["run", "start"]
working_dir = "/app"

[triggers.build_integration]
command = "mono"
args = ["build"]
working_dir = "/integration"
