services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
  redis:
    image: "redis:6.2.7"
  appsignal-agent:
    image: appsignal/agent:local_linux_amd64
    environment:
      - APPSIGNAL_APP_NAME=ruby/rails-sidekiq-opentelemetry
      - APPSIGNAL_APP_ENV=development
      - APPSIGNAL_LOG_LEVEL=trace
    env_file:
      - ../../appsignal_key.env
  app:
    build: .
    image: ruby/rails7-sidekiq-opentelemetry
    depends_on:
      - postgres
      - redis
    ports:
      - "4001:4001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://appsignal-agent:8099/enriched
      - APPSIGNAL_APP_NAME=ruby/rails7-sidekiq-opentelemetry-from-resource
      - APPSIGNAL_APP_ENV=development
      - PORT=4001
    env_file:
      - postgres.env
      - redis.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=ruby/rails7-sidekiq-opentelemetry
      - APP_URL=http://app:4001
