#!/bin/bash

set -eu

echo "Install AppSignal"
(
  cd /integration
  rake extension:install
)

cd /app
echo "Install dependencies"
bundle config set --local path 'vendor/bundle'
bundle install
yarn install

echo "Clean tmp"
rm -rf tmp
mkdir -p tmp/pids tmp/sockets

echo "Running migrations"
bin/rails db:migrate

/commands/processmon processmon.toml
