#!/bin/bash

set -eu

echo "Running mix local hex and rebar"
mix local.hex --force
mix local.rebar --force

cd /app
echo "Running mix deps.get"
mix deps.get

echo "Migrate if needed"
mix ecto.migrate

mix run --no-halt
