version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./app:/app
    environment:
      OTEL_SERVICE_NAME: "spring-boot"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://appsignal-collector:8099"
      APPSIGNAL_APP_NAME: java/spring-boot
      APPSIGNAL_APP_ENV: development
    env_file:
      - ../../appsignal_key.env
    ports:
      - "4001:8080"
    depends_on:
      - appsignal-collector
  appsignal-collector:
    image: appsignal/collector:latest
    environment:
      - APPSIGNAL_LOG_LEVEL=trace
    env_file:
      - ../../appsignal_key.env
