#!/bin/bash
set -eu

cd /app

# Paths for Puma
mkdir -p shared/sockets shared/pids shared/log

echo "Install dependencies"
bundle config set path vendor/bundle
bundle install

echo "Starting app"
bundle exec puma --environment production --control-url $PUMA_URL --control-token $PUMA_TOKEN
