#!/bin/bash

set -eu

echo "Installing compatible NPM version"
npm install -g npm@7.18.1

echo "Install, link and build integration"
(
cd /integration
git checkout main
touch ~/.bashrc # hack to make the mono installer happy
script/setup
mono bootstrap
mono clean
mono run -- npm run install
mono build
)

cd /app

echo "Installing app dependencies"
npm install

echo "Linking integration"
npm link @appsignal/nodejs

echo "Building app"
npm run build

echo "Starting test app server"
/commands/processmon processmon.toml
