version: '3.8'

services:
  app:
    build: .
    image: ruby/padrino
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=ruby-padrino
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
