version: '3.8'

services:
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE # To silent non-important errors
    env_file:
      - mysql.env
  app:
    build: .
    platform: linux/amd64
    image: ruby/rails6-mysql
    depends_on:
      - mysql
    ports:
      - "4001:4001"
    environment:
      - APPSIGNAL_APP_NAME=ruby-rails6-mysql
      - PORT=4001
    env_file:
      - mysql.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    build: ../../support/server-tests
    image: server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=ruby/rails6-mysql
      - APP_URL=http://app:4001
