#!/bin/bash

set -eu

echo "Installing compatible NPM version"
npm install -g npm@latest

# The following block is commented because of an issue with
# Next.js' internal use of Webpack and `npm link`-ed projects.
# Instead, this test setup ignores the version of the integrations
# cloned by `rake integrations:clone`, and installs and uses the
# latest released version from the NPM servers.

# echo "Install, link and build integration"
# (
# cd /integration
# git checkout main
# touch ~/.bashrc # hack to make the mono installer happy
# script/setup
# mono bootstrap
# mono clean
# mono run -- npm run install
# mono build
# )

cd /app

echo "Installing app dependencies"
npm install

# See comment above.

# echo "Linking integration"
# npm link @appsignal/nodejs

echo "Starting the app in NODE_ENV='$NODE_ENV' (default: development)"
if [ "$NODE_ENV" == "production" ]; then
  npm run build
  npm run start
else
  npm run dev
fi
