version: "3.8"

services:
  rabbitmq:
    image: rabbitmq
    restart: always
  app:
    build: .
    depends_on:
      - rabbitmq
    image: nodejs/express-rabbitmq
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - APPSIGNAL_APP_NAME=nodejs-v3-express-rabbitmq
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    working_dir: /
    volumes:
      - ./app:/app
      - ../integration:/integration
  tests:
    image: server-tests
    build: ../../support/server-tests
    profiles:
      - tests
    depends_on:
      - app
    environment:
      - APP_NAME=nodejs/v3/express-rabbitmq
      - APP_URL=http://app:4001
