[[paths_to_watch]]
path = "/app"
ignore = ["__pycache__"]

[processes.django]
command = "python3"
args = [
  "-m",
  "uvicorn",
  "appsignal_python_opentelemetry.asgi:application",
  "--host",
  "0.0.0.0"
]
working_dir = "/app"
