[[paths_to_watch]]
path = "/app"

[processes.django]
command = "python3"
args = [
  "-m",
  "uvicorn",
  "appsignal_python_opentelemetry.asgi:application",
  "--host",
  "0.0.0.0"
]
working_dir = "/app"

[processes.celery]
command = "celery"
args = [
  "--app=tasks",
  "worker",
  "--loglevel=INFO",
  "--queues=high-priority,low-priority"
]
working_dir = "/app"
