#!/bin/bash
set -eu

echo "Running mix local hex and rebar"
mix local.hex --force
mix local.rebar --force

echo "Prepare integration"
cd /integration/appsignal-elixir
make clean

cd /app
echo "Running mix deps.get"
mix deps.get

echo "Running migrations"
mix ecto.migrate

mix run --no-halt
