version: "3.8"

services:
  nginx:
    build: nginx
    ports:
      - "4001:4001"
    links:
      - agent
    volumes:
      - ./app:/app

  agent:
    image: appsignal/agent:latest
    environment:
      - APPSIGNAL_APP_NAME=nginx-metrics-standalone-test
      - APPSIGNAL_APP_ENV=development
      - APPSIGNAL_LOG_LEVEL=trace
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
