[[paths_to_watch]]
path = "/app"
ignore = [
  "tmp",
  "log",
  "node_modules",
  "public/packs"
]

[[paths_to_watch]]
path = "/integration"

[processes.sidekiq]
command = "bundle"
args = [
  "exec",
  "sidekiq",
  "--queue=default"
]
working_dir = "/app"

[processes.rails]
command = "bin/rails"
args = [
  "server",
  "--binding=0.0.0.0",
  "--port=4001"
]
working_dir = "/app"

bin/rails server --binding=0.0.0.0 --port=4001
bundle exec sidekiq --queue=default
bundle exec puma --port=4001 --environment development
