version: '3.8'

services:
  app:
    build: .
    image: nodejs/express-apollo
    ports:
      - "4001:3000"
    environment:
      - APPSIGNAL_APP_NAME=nodejs-express-apollo
    env_file:
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
