version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
  redis:
    image: "redis:6.0"
  app:
    build: .
    image: nodejs/express-postgres
    depends_on:
      - postgres
      - redis
    ports:
      - "4001:3000"
    environment:
      - APPSIGNAL_APP_NAME=nodejs-express-postgres
      - PORT=4001
    env_file:
      - postgres.env
      - redis.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
