version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
  app:
    image: nodejs/express-postgres:latest
    depends_on:
      - postgres
    ports:
      - "4001:3000"
    environment:
      - APPSIGNAL_APP_NAME=nodejs-express-postgres
    env_file:
      - postgres.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
