{application,tailwind,
             [{optional_applications,[inets,ssl]},
              {applications,[kernel,stdlib,elixir,logger,inets,ssl]},
              {description,"Mix tasks for installing and invoking tailwind"},
              {modules,['Elixir.Mix.Tasks.Tailwind',
                        'Elixir.Mix.Tasks.Tailwind.Install',
                        'Elixir.Tailwind']},
              {registered,[]},
              {vsn,"0.4.1"},
              {mod,{'Elixir.Tailwind',[]}},
              {env,[{default,[]}]}]}.
