version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - 5432
  app:
    build: .
    image: elixir/phoenix-example
    depends_on:
      - postgres
    ports:
      - "4001:4000"
    environment:
      - APPSIGNAL_APP_NAME=elixir-phoenix-example
      - INTEGRATION_PATH=/integration
    env_file:
      - postgres.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - ./app:/app
      - ../integration:/integration
