version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
  app:
    build: .
    image: elixir/phoenix-example
    depends_on:
      - postgres
    ports:
      - "4001:4000"
    environment:
      - APPSIGNAL_APP_NAME=elixir-phoenix-example
    env_file:
      - postgres.env
      - ../../appsignal.env
      - ../../appsignal_key.env
    volumes:
      - "nfsmount_app:/app"
      - "nfsmount_integration:/integration"

volumes:
  nfsmount_app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/app"
  nfsmount_integration:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/../integration"
