#!/bin/bash
set -eu

(
  echo "Install, link and build integration"
  cd /integration
  script/setup
  mono bootstrap
  mono clean
  mono build --package=@appsignal/javascript,@appsignal/ember
)

cd /app

echo "Install dependencies"
npm install
npm link @appsignal/javascript @appsignal/ember

echo "Starting app"
npm run start
