#!/bin/bash

set -eu

echo "Running mix local hex and rebar"
mix local.hex --force
mix local.rebar --force

cd /app
echo "Running mix deps.get"
mix deps.get

echo "Running npm install"
(cd /app/assets && npm install)

echo "Migrate if needed"
mix ecto.migrate

PHX_HOST=localhost PORT=4000 SECRET_KEY_BASE=HyuxwmHChOY0mqToau8TyFaoV1wIgZbQMdiyD2AzMIdLs2c1FvSG5ZJuXESBDYDJ MIX_ENV=prod mix phx.server
