#!/bin/bash
set -eu

echo "Install appsignal"
cd /integration
rake extension:install

cd /app
echo "Install dependencies"
bundle config set --local path 'vendor/bundle'
bundle install

/commands/processmon processmon.toml
