#!/bin/bash

set -eu

echo "Installing compatible NPM version"
npm install -g npm@latest

# echo "Install, link and build integration"
# (
# cd /integration
# git checkout main
# touch ~/.bashrc # hack to make the mono installer happy
# script/setup
# mono bootstrap
# mono clean
# mono run -- npm run install
# mono build
# )

cd /app

echo "Installing app dependencies"
npm install

echo "Linking integration"
# npm link @appsignal/nodejs

echo "Starting the app"
npm run dev
